- Bugfixes for sending status output to a file
(Logical change 1.72)

diff --git a/scripts/lmbench b/scripts/lmbench
--- a/scripts/lmbench
+++ b/scripts/lmbench
@@ -11,9 +11,9 @@ PATH=.:../../scripts:$PATH:/etc:/usr/etc:/sbin:/usr/sbin
 export PATH
 
 if [ -f $1 ]
-then	echo Using config in $1 > ${OUTPUT}
-	. $1
-else	echo Using defaults > ${OUTPUT}
+then	. $1
+	echo Using config in $1 >> ${OUTPUT}
+else	echo Using defaults >> ${OUTPUT}
 	ENOUGH=1000000
 	TIMING_O=0
 	LOOP_O=0
@@ -23,7 +23,7 @@ export ENOUGH TIMING_O LOOP_O SYNC_MAX LINE_SIZE
 
 if [ X$FILE = X ]
 then	FILE=/tmp/XXX
-	touch $FILE || echo Can not create $FILE
+	touch $FILE || echo Can not create $FILE >> ${OUTPUT}
 fi
 if [ X$MB = X ]
 then	MB=8
@@ -120,7 +120,7 @@ STAT=$FSDIR/lmbench
 mkdir $FSDIR 2>/dev/null
 touch $STAT 2>/dev/null
 if [ ! -f $STAT ]
-then	echo "Can't make a file - $STAT - in $FSDIR" > ${OUTPUT}
+then	echo "Can't make a file - $STAT - in $FSDIR" >> ${OUTPUT}
 	touch $STAT
 	exit 1
 fi
@@ -128,13 +128,13 @@ if [ X$SYNC != X ]
 then	/bin/rm -rf $SYNC
 	mkdir -p $SYNC 2>/dev/null
 	if [ ! -d $SYNC ]
-	then	echo "Can't make $SYNC"
+	then	echo "Can't make $SYNC" >> ${OUTPUT}
 		exit 1
 	fi
 fi
 
-date > ${OUTPUT}
-echo Latency measurements > ${OUTPUT}
+date >> ${OUTPUT}
+echo Latency measurements >> ${OUTPUT}
 if [ X$BENCHMARK_OS = XYES -o X$BENCHMARK_SYSCALL = XYES ]; then
 	lat_syscall -P $SYNC_MAX null
 	lat_syscall -P $SYNC_MAX read
@@ -205,8 +205,8 @@ if [ X$BENCHMARK_OS = XYES -o X$BENCHMARK_MMAP = XYES ]; then
 fi
 if [ X$BENCHMARK_OS = XYES -o X$BENCHMARK_FILE = XYES ]; then
 	if [ X$SLOWFS != XYES ]
-	then	date > ${OUTPUT}
-		echo Calculating file system latency > ${OUTPUT}
+	then	date >> ${OUTPUT}
+		echo Calculating file system latency >> ${OUTPUT}
 		echo '"File system latency' 1>&2
 		lat_fs -P $SYNC_MAX $FSDIR
 		echo "" 1>&2
@@ -218,7 +218,7 @@ if [ X$BENCHMARK_HARDWARE = XYES ]; then
 	then	for i in $DISKS
 		do	if [ -r $i ]
 			then	echo "Calculating disk zone bw & seek times" \
-					> ${OUTPUT}
+					>> ${OUTPUT}
 				disk $i
 				echo "" 1>&2
 			fi
@@ -226,8 +226,8 @@ if [ X$BENCHMARK_HARDWARE = XYES ]; then
 	fi
 fi
 
-date > ${OUTPUT}
-echo Local networking > ${OUTPUT}
+date >> ${OUTPUT}
+echo Local networking >> ${OUTPUT}
 if [ ! -d ../../src/webpage-lm ]
 then	(cd ../../src && tar xf webpage-lm.tar)
 	sync
@@ -277,7 +277,7 @@ lat_http -S localhost 8008
 
 for remote in $REMOTE 
 do
-	echo Networking to $remote > ${OUTPUT}
+	echo Networking to $remote >> ${OUTPUT}
 	$RCP $SERVERS lmhttp ../../src/webpage-lm.tar ${remote}:/tmp
 	for server in $SERVERS
 	do	$RSH $remote -n /tmp/$server -s &
@@ -329,8 +329,8 @@ do
 	$RSH $remote rm $RM
 done
 
-date > ${OUTPUT}
-echo Bandwidth measurements > ${OUTPUT}
+date >> ${OUTPUT}
+echo Bandwidth measurements >> ${OUTPUT}
 
 if [ X$BENCHMARK_OS = XYES -o X$BENCHMARK_UNIX = XYES ]; then
 	bw_unix -P $SYNC_MAX 
@@ -403,9 +403,9 @@ if [ X$BENCHMARK_OS = XYES -o X$BENCHMARK_HARDWARE = XYES \
 fi
 
 if [ X$BENCHMARK_OS = XYES -o X$BENCHMARK_CTX = XYES ]; then
-	date > ${OUTPUT}
+	date >> ${OUTPUT}
 	msleep 250
-	echo Calculating context switch overhead > ${OUTPUT}
+	echo Calculating context switch overhead >> ${OUTPUT}
 	if [ $MB -ge 8 ]
 	then	CTX="0 4 8 16 32 64"
 		N="2 4 8 16 24 32 64 96"
@@ -422,32 +422,32 @@ if [ X$BENCHMARK_OS = XYES -o X$BENCHMARK_CTX = XYES ]; then
 fi
 
 if [ X$BENCHMARK_HARDWARE = XYES -o X$BENCHMARK_MEM = XYES ]; then
-	date > ${OUTPUT}
+	date >> ${OUTPUT}
 	msleep 250
-	echo Calculating effective TLB size > ${OUTPUT}
+	echo Calculating effective TLB size >> ${OUTPUT}
 	tlb -L $LINE_SIZE -M ${MB}M
 	echo "" 1>&2
 
-	date > ${OUTPUT}
+	date >> ${OUTPUT}
 	msleep 250
-	echo Calculating memory load parallelism > ${OUTPUT}
+	echo Calculating memory load parallelism >> ${OUTPUT}
 	echo "Memory load parallelism" 1>&2
 	par_mem -L $LINE_SIZE -M ${MB}M
 	echo "" 1>&2
 
-	date > ${OUTPUT}
+	date >> ${OUTPUT}
 	msleep 250
-	echo Calculating cache parameters > ${OUTPUT}
+	echo Calculating cache parameters >> ${OUTPUT}
 	cache -L $LINE_SIZE -M ${MB}M
 
-	date > ${OUTPUT}
+	date >> ${OUTPUT}
 	msleep 250
-	echo McCalpin\'s STREAM benchmark > ${OUTPUT}
+	echo McCalpin\'s STREAM benchmark >> ${OUTPUT}
 	stream -M ${MB}M
 
-	date > ${OUTPUT}
+	date >> ${OUTPUT}
 	msleep 250
-	echo Calculating memory load latency > ${OUTPUT}
+	echo Calculating memory load latency >> ${OUTPUT}
 	echo "Memory load latency" 1>&2
 	if [ X$FASTMEM = XYES ]
 	then	lat_mem_rd -P $SYNC_MAX $MB 128
@@ -456,7 +456,7 @@ if [ X$BENCHMARK_HARDWARE = XYES -o X$BENCHMARK_MEM = XYES ]; then
 	echo "" 1>&2
 fi
 
-date > ${OUTPUT}
+date >> ${OUTPUT}
 echo '' 1>&2
 echo \[`date`] 1>&2
 
